version: "3.8"

services:
    mysql_db_container:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            DB_PATH_HOST: /tmp/mysql #this is the host location where mysql data will be stored.
        ports:
            - 3306:3306
        volumes:
            - shared_database:/var/lib/mysql
        #network_mode: host
    adminer_container:
        image: adminer:latest
        depends_on:
            - mysql_db_container
        environment:
            ADMINER_DEFAULT_SERVER: mysql_db_container
        ports:
            - 8080:8080
       # network_mode: host

    nodejs-api:
        image: angeld11235/ts-clone-nodejs:latest
        restart: always
        environment:
           MYSQL_DB_ADDRESS: mysql_db_container
            #- NODE_ENV=production
            # - PORT=3000
        ports:
            - "3000:3000"
        depends_on:
            - mysql_db_container #make sure mongo is running
        #network_mode: host
        # networks:
        #     default:
        #         ipv4_address: 172.16.238.10


    strapi:
        image: strapi/strapi
        environment:
          DATABASE_CLIENT: mysql
          DATABASE_HOST: mysql
          DATABASE_PORT: 3306
          DATABASE_NAME: myWebsiteAPI
          DATABASE_USERNAME: root 
          DATABASE_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
          DATABASE_SSL: 'false'
        volumes:
          - ./app:/srv/app
        ports:
          - '1337:1337'
        depends_on:
          - mysql_db_container

volumes:
    shared_database: